#!/usr/bin/python3
#!SPDX-FileCopyrightText: 2024 Kosuke Abe
#!SPDX-License-Identifier: BSD-3-Clause

import sys
from datetime import datetime

def calculate_weekday(year, month, day, is_leap_year):
    month_numbers = {
        1: 1 if not is_leap_year else 0,
        2: 4 if not is_leap_year else 3,
        3: 4,
        4: 0,
        5: 2,
        6: 5,
        7: 0,
        8: 3,
        9: 6,
        10: 1,
        11: 4,
        12: 6
    }
    century_number = 6 if year >= 2000 else 0
    total = (day + year % 100 + (year % 100) // 4 + month_numbers[month] + century_number) % 7
    return ["土曜日", "日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日"][total]

def is_valid_date(year, month, day):
    try:
        datetime(year, month, day)
        return True
    except ValueError:
        return False

if __name__ == "__main__":
    try:
        if not sys.stdin.isatty():
            year, month, day, leap = sys.stdin.read().strip().split('/')
            is_leap = leap.lower() == "yes"

            
            year, month, day = int(year), int(month), int(day)
            if not is_valid_date(year, month, day):
                print(f"エラー: 無効な日付が入力されました。", file=sys.stderr)
                sys.exit(1)

            
            weekday = calculate_weekday(year, month, day, is_leap)
            print(f"{year}/{month}/{day}は{weekday}です。")
        else:
            print("標準入力からデータを提供してください", file=sys.stderr)
            sys.exit(1)
    except Exception as e:
        print(f"エラー: {e}", file=sys.stderr)
        sys.exit(1)

